[workspace]
members = ["nodetree-core", "nodetree-server"]

[workspace.dependencies]
anyhow = "1.0.75"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
chrono = { version = "0.4.35", features = ["serde"] }
